kind: pipeline
name: default

steps:
  - name: build image
    image: docker:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build --no-cache -t test-ci:latest .

  - name: run tests
    image: test-ci:latest
    pull: if-not-exists
    commands:
      - npm test

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
