version: '1.0'
stages:
  - clone
  - build
  - test
steps:
  main_clone:
    type: git-clone
    description: Cloning main repository...
    repo: SpellChucker/test-ci
    revision: ${{CF_BRANCH}}
    stage: clone
  build_image:
    title: Building Image
    type: build
    image-name: SpellChucker/test-ci
    working_directory: ${{main_clone}}
    dockerfile: Dockerfile
    tag: ${{CF_BRANCH}}
    stage: build
  unit_tests:
    title: Running Tests
    image: ${{build}}
    fail-fast: false
    commands:
      - npm test
    stage: test
